### PR TITLE
f-fix/gh-826-requests-table

### LINKED ISSUE #826: Requests table broken
image

### PR DESCRIPTION
**Pull request by ffpetrovic**
Closes #826

### CODE REVIEW

File: src/main/frontend/src/components/common/TableStyledComponents.js [hunk 1]
```diff
@@ -52,6 +52,17 @@ export const TableHeader = styled.div`
...
+export const TableHeaderNative = styled.th`
+  ${props => sharedStyle(props.color, props.borderless)}
+  font-size: 18px;
+  height: 50px;
+  flex: 1 1 0;
+
+  @media (max-width: 992px) {
+    display: none;
+  }
+`;
```
Comment (aberonja) [inline src/main/frontend/src/components/common/TableStyledComponents.js]: /n
