### PR TITLE
f-fix/gh-1017-check-personalData

### LINKED ISSUE #1017: Manually changing leave profile for employee crashes the application
Steps to reproduce (must have HR_MANAGER role):
- Go to administration and select Employees tab
- Find your profile information and change leave profile
- Save the change, and go to the dashboard

Expected result:

- New leave profile is set and the corresponding allowance values are set

Actual result:

- Application crashes with an error message (image below)
Screenshot from 2019-10-23 13-35-11

### PR DESCRIPTION
**Pull request by petarkovac**
Resolves #1017

### CODE REVIEW

File: src/main/frontend/src/components/calendar/calendarUtils.js [hunk 1]
```diff
@@ -63,7 +63,7 @@ const checkIfPublicHoliday = (day, publicHolidays, personalData) => {
 const checkIfUserDay = dayObject => {
   const { day, publicHoliday, personalData } = dayObject;
 
-  if (!personalData.length) {
+  if (personalData !== undefined && !personalData.length) {
```
Comment (iscekic) [inline src/main/frontend/src/components/calendar/calendarUtils.js]:
```suggestion
  if (personalData != null && !personalData.length) {
```

This checks for both `null` and `undefined`. 💃

**Comment by petarkovac** [comment]
Resolves:  #972
