### PR TITLE
f-fix/gh-784-table-scroll-after-create

### LINKED ISSUE #784: Infinite scroll issue
When creating new year/team/employee/leavetype/leaveprofile set scroll to the top because otherwise it will trigger infinity scroll without need.

year-create

Check the network tab!

@BraneOpacic21 made something that can be reused. Ask him for more info.

### PR DESCRIPTION
**Pull request by ffpetrovic**
Closes #784

### CODE REVIEW

File: src/main/frontend/src/pages/administration/components/common/AdministrationTable.js [hunk 1]
```diff
@@ -18,21 +18,30 @@ import {
...
   componentWillMount() {
     this.delayedCallback = _debounce(({ target: { value } }) => {
       this.employeeSearch(value);
     }, 500);
   }
 
+  componentDidUpdate() {
+    if (this.props.administration.shouldTableScrollToTop) {
+      this.props.setShouldTableScrollToTop(false);
+      this.tableRef.current.scrollTop = 0;
```
Comment (aberonja) [inline src/main/frontend/src/pages/administration/components/common/AdministrationTable.js]: Please, change the order of these two. I know it won't make any difference, but it will to someone who's reading the code for the first time.

File: src/main/frontend/src/pages/administration/components/common/styled.js [hunk 2]
```diff
@@ -20,14 +20,16 @@ export const TableContent = styled.div`
   height: 0;
   overflow-x: auto;
   overflow-y: auto;
```
Comment (aberonja) [inline src/main/frontend/src/pages/administration/components/common/styled.js]: /n
