### PR TITLE
F fix/gh 787 administration responsive

### LINKED ISSUE #787: Administration responsive
Fix responsive on administration

### PR DESCRIPTION
**Pull request by ffpetrovic**
image

Closes #787

### CODE REVIEW

File: src/main/frontend/src/pages/administration/components/teams/Images.js [hunk 1]
```diff
@@ -6,61 +6,56 @@ import { getImageUrl } from '../../../../store/getImageUrl';
 import { NumberSpan } from './styled';
 
 class Images extends Component {
-  generateImageItems = items => {
-    const imageItems = [];
-
-    for (let i = 0; i < 5; i++) {
+  generateImageItems = items =>
+    Array.from({ length: 5 }, (_, i) => {
```
Comment (aberonja) [inline src/main/frontend/src/pages/administration/components/teams/Images.js]: Noice 🌜
