### PR TITLE
f-fix/gh-848-public-holidays-same-data-twice

### LINKED ISSUE #848: Public holidays same data twice
image

### PR DESCRIPTION
**Pull request by aberonja**
Closes #848

### CODE REVIEW

File: src/main/frontend/src/pages/administration/components/common/AdministrationTable.js [hunk 1]
```diff
@@ -196,7 +194,7 @@ class AdministrationTable extends Component {
                 loadMore={this.loadMore}
                 hasMore={!last}
                 threshold={50}
-                initialLoad={false}
+                initialLoad={initialLoad || false}
```
Comment (ffpetrovic) [inline src/main/frontend/src/pages/administration/components/common/AdministrationTable.js]: `{initialLoad}`

Comment (aberonja) [reply src/main/frontend/src/pages/administration/components/common/AdministrationTable.js]: It won't work if I make it like that, trust me 😄
initialLoad
