### PR TITLE
f-fix/gh-785-public-holidays-accordion

### LINKED ISSUE #785: Public holidays accordion
- Implement bootstrap accordion on Public Holidays tab
- Remove fetching on item accordion close
- Allow having multiple accordions open
- Check with the rest of the team should you have all created years available to open even if there are no holidays created for selected year

### PR DESCRIPTION
**Pull request by ffpetrovic**
Closes #785

### CODE REVIEW

File: src/main/frontend/src/pages/administration/components/public-holidays/HolidaysYear.js [hunk 1]
```diff
@@ -12,14 +12,34 @@ import { getPublicHolidays } from '../../../../store/selectors';
...
+      expandAccordion,
+      requestPublicHolidaysByYear
+    } = this.props;
+
+    if (!publicHolidays.results[year]) {
+      requestPublicHolidaysByYear({
+        year: year
+      });
+    } else if (publicHolidays.accordionExpanded[year]) {
+      expandAccordion({ year: year, expanded: false });
```
Comment (aberonja) [inline src/main/frontend/src/pages/administration/components/public-holidays/HolidaysYear.js]: Can this become a toggle action?
