### PR TITLE
b-enhancement/gh-978-employee-date-validation

### LINKED ISSUE #978: No date validation when creating employee career dates
Steps to reproduce:

- Log in as  HR Manager
- Go to Administration page
- Select Employees tab
- Create new employee
- Edit the following fields: Started professional career date , Started working date, Started working at execom date, with random future dates.

Expected result: There are restrictions like "Started working at execom date" cannot be before "Started working date"
Actual result: There are no restrictions when entering dates; "Years of Service" field gets a negative value.

Employee_date_validation

### PR DESCRIPTION
**Pull request by petarkovac**
Throws runtime exception when:
-Started working at Execom date is before started working date
-Started professional career date is after started working date at Execom
Resolves #978

### CODE REVIEW

File: src/main/java/eu/execom/hawaii/exceptions/DateValidationException.java [hunk 1]
```diff
@@ -0,0 +1,9 @@
+package eu.execom.hawaii.exceptions;
+
+public class DateValidationException extends RuntimeException {
```
Comment (stanislavgrujic) [inline src/main/java/eu/execom/hawaii/exceptions/DateValidationException.java]: Please be more specific when naming classes - e.g, *DateOutOfScopeException*.
