### PR TITLE
f-fix/gh-807-table-header-jump

### LINKED ISSUE #807: Table header jump
When switching from teams to employees tab table header has a slight jump.

table-header-jump

### PR DESCRIPTION
**Pull request by ffpetrovic**
This change is introduced to fix the jump that occurs in the table
header, when switching to
and from the Employees tab.

Closes #807

### CODE REVIEW

File: src/main/frontend/src/components/common/TableStyledComponents.js [hunk 1]
```diff
@@ -38,9 +38,14 @@ export const TableCell = styled(TableCellBasic)`
...
 
-export const TableHeader = styled.th`
+export const TableHeader = styled.div`
   ${props => sharedStyle(props.color, props.borderless)}
   font-size: 18px;
+  flex-grow: 1;
+  flex-basis: 0;
+  height: 50px;
+  display: flex;
+  align-items: center;
```
Comment (aberonja) [inline src/main/frontend/src/components/common/TableStyledComponents.js]: Use bootstrap classes when possible.

File: src/main/frontend/src/pages/administration/components/common/styled.js [hunk 2]
```diff
@@ -9,8 +9,12 @@ export const FixedTable = styled.table`
 `;
 
 export const FilterIconsWrapper = styled.div`
+  display: flex;
+  align-items: center;
```
Comment (aberonja) [inline src/main/frontend/src/pages/administration/components/common/styled.js]: Bootstrap classes

File: src/main/frontend/src/pages/administration/components/common/styled.js [hunk 3]
```diff
@@ -39,6 +43,7 @@ const SearchBarInput = styled.input`
 
 const SearchBarWrapper = styled.div`
   position: relative;
+  width: 100%;
```
Comment (aberonja) [inline src/main/frontend/src/pages/administration/components/common/styled.js]: Both of these can be bootstrap classes, no need for styled component
