### PR TITLE
f-fix/gh-863-team-edit-employees

### LINKED ISSUE #849: Remove tabs if there is only one possibility
image

### LINKED ISSUE #861: FAB Covering last item in table
image

### LINKED ISSUE #863: Team edit employees
While editing team only newly added employees can be removed. Mark "X" to the right of employee indicating removal of the same should only be displayed next to newly added employee to the team (during that edit).

### PR DESCRIPTION
**Pull request by ffpetrovic**
- Hide/show "+" FAB depending on scroll
 - Add color to Request status text
 - Swap places of "+" and filter buttons in employees
 - Fix error border for date inputs in sidebar
 - Remove tab navigation in sidebar if only one tab is needed
 - Add table cell for when user is scheduled for restoration
 - Keep "x" delete button on approvers only on approvers not already in team

Closes #863
Closes #861
Closes #849

### CODE REVIEW

File: src/main/frontend/src/components/common/FloatingActionButton/styled.js [hunk 1]
```diff
@@ -1,5 +1,14 @@
 import styled from 'styled-components';
 
+export const FabWrapper = styled.div`
+  opacity: ${props => (props.hide ? '0' : '1')};
+  ${props => (props.hide ? 'pointer-events: none' : '')};
+  display: block;
```
Comment (aberonja) [inline src/main/frontend/src/components/common/FloatingActionButton/styled.js]: bootstrap class

File: src/main/frontend/src/components/common/FloatingActionButton/styled.js [hunk 2]
```diff
@@ -1,5 +1,14 @@
...
+  transition: opacity 0.2s;
+  z-index: 10;
+  position: relative;
```
Comment (aberonja) [inline src/main/frontend/src/components/common/FloatingActionButton/styled.js]: bootstrap class

File: src/main/frontend/src/pages/administration/components/common/AdministrationTable.js [hunk 3]
```diff
@@ -181,37 +183,40 @@ class AdministrationTable extends Component {
...
                     />
-                    <FilterIcon
-                      onClick={() => this.handleFilters(ACTIVE)}
-                      src={ActiveUsers}
-                      isSelected={userStatusType.includes(ACTIVE)}
-                    />
                   </FilterIconsWrapper>
                 )}
+                <RoundButton
+                  click={() => clickAction()}
```
Comment (aberonja) [inline src/main/frontend/src/pages/administration/components/common/AdministrationTable.js]: ?

Comment (aberonja) [reply src/main/frontend/src/pages/administration/components/common/AdministrationTable.js]: clickAction

File: src/main/frontend/src/pages/administration/components/teams/EditTeam.js [hunk 4]
```diff
@@ -189,14 +189,20 @@ class EditTeam extends Component {
...
-                                  className="text-danger ml-2"
-                                  onClick={() => {
-                                    arrayHelpers.remove(index);
-                                  }}
-                                >
-                                  x
-                                </span>
+                                <Fragment>
+                                  {!this.props.team.users.find(
+                                    u => u.id === user.id
```
Comment (aberonja) [inline src/main/frontend/src/pages/administration/components/teams/EditTeam.js]: More descriptive
